eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY:e3cbc7cca57d111913d50b0c0b4075b5bc2e6265da68bcdaf325b9132b8eb57e}
    expiration-time: ${SECURITY_JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
